steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/peppy-oven-444016-g6/mlgc/asclepius",
        ".",
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
         "asia-southeast2-docker.pkg.dev/peppy-oven-444016-g6/mlgc/asclepius",
      ]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "asclepius"
      - "--image"
      -  "asia-southeast2-docker.pkg.dev/peppy-oven-444016-g6/mlgc/asclepius",
      - "--platform"
      - "managed"
      - "--region"
      - "<sesuaikan dengan lokasi deploy firestore>"
      - "--allow-unauthenticated"
options:
  logging: CLOUD_LOGGING_ONLY
images:
  -  "asia-southeast2-docker.pkg.dev/peppy-oven-444016-g6/mlgc/asclepius",
